services:
  app:
    container_name: app
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - .:/var/www/source

  db:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./db:/var/lib/postgresql/data
